steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--build-arg=SSH_PRIVATE_KEY=$_SSH_PRIVATE_KEY_'
    - '--build-arg=KNOWN_HOSTS=$_KNOWN_HOSTS_'
    - '-t'
    - 'gcr.io/YOUR_PROJECT_ID/my_flutter_image'
    - '.'

# Step 2: Push the Docker image to Google Container Registry (GCR)
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/YOUR_PROJECT_ID/my_flutter_image']

images:
# Specify the Docker image to be pushed to GCR
- 'gcr.io/YOUR_PROJECT_ID/my_flutter_image'
