steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--build-arg=SSH_PRIVATE_KEY=$_SSH_PRIVATE_KEY_'
    - '-t'
    - 'gcr.io/$_PROJECT_ID_/$_IMAGE_NAME_'
    - '.'


# Step 2: Push the Docker image to Google Container Registry (GCR)
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$_PROJECT_ID_/$_IMAGE_NAME_']

# Step 3: Deploy the Docker image to Cloud Run
- name: "gcr.io/cloud-builders/gcloud"
  args:
    - "run"
    - "deploy"
    - "$_IMAGE_NAME_"
    - "--image=gcr.io/$_PROJECT_ID_/$_IMAGE_NAME_"  # Replace 'latest' with your desired image tag
    - "--region=australia-southeast1"
    - "--platform=managed"
    - "--allow-unauthenticated"

options:
  logging: CLOUD_LOGGING_ONLY
