steps:
  # Step 1: Build the Docker image
  # - name: 'gcr.io/cloud-builders/docker'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       docker build \
  #         --build-arg SSH_PRIVATE_KEY="$$_SSH_PRIVATE_KEY_" \
  #         -t gcr.io/${_PROJECT_ID_}/${_IMAGE_NAME_} \
  #         .
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg SSH_PRIVATE_KEY="$$ED_WIDGET_SSH_KEY" \
          --build-arg _GUMMY_BEARS_URL=${_SSH_PRIVATE_KEY_} \
          --build-arg _VALIDATE_FIREBASE_ID_TOKEN_ENTRYPOINT=${_SSH_PRIVATE_KEY_} \
          --build-arg _ENV_MODE=${_SSH_PRIVATE_KEY_} \      
          -t ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/edapp-repo/${_DEPLOY_NAME}:${SHORT_SHA} \ 
          .

    secretEnv: ['_SSH_PRIVATE_KEY_']

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$_PROJECT_ID_/$_IMAGE_NAME_']

  # Step 3: Deploy the Docker image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "$_IMAGE_NAME_"
      - "--image=gcr.io/$_PROJECT_ID_/$_IMAGE_NAME_"  # Replace 'latest' with your desired image tag
      - "--region=australia-southeast1"
      - "--platform=managed"
      - "--allow-unauthenticated"

availableSecrets:
  secretManager:
    - versionName: projects/918746432463/secrets/_SSH_PRIVATE_KEY_/versions/1
      env: '_SSH_PRIVATE_KEY_'

options:
  logging: CLOUD_LOGGING_ONLY


# steps:
#   - name: 'gcr.io/cloud-builders/docker'
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         docker build \
#           --build-arg SSH_PRIVATE_KEY="$$ED_WIDGET_SSH_KEY" \
#           --build-arg _GUMMY_BEARS_URL=${_SSH_PRIVATE_KEY_} \
#           --build-arg _VALIDATE_FIREBASE_ID_TOKEN_ENTRYPOINT=${_SSH_PRIVATE_KEY_} \
#           --build-arg _ENV_MODE=${_SSH_PRIVATE_KEY_} \      
#           -t ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/edapp-repo/${_DEPLOY_NAME}:${SHORT_SHA} \ 
#           .
#     secretEnv: ['ED_WIDGET_SSH_KEY']      

 
#   - name: "gcr.io/cloud-builders/docker"
#     args: ["push", "$LOCATION-docker.pkg.dev/$PROJECT_ID/edapp-repo/${_DEPLOY_NAME}:${SHORT_SHA}"]
    

#   - name: "gcr.io/cloud-builders/gcloud"
#     args:
#       [
#         "run",
#         "deploy",
#         "${_DEPLOY_NAME}",
#         "--image",
#         "$LOCATION-docker.pkg.dev/$PROJECT_ID/edapp-repo/${_DEPLOY_NAME}:${SHORT_SHA}",
#         "--region",
#         "australia-southeast1",
#         "--platform",
#         "managed",
#         --allow-unauthenticated,
#       ]

# availableSecrets:
#   secretManager:
#   - versionName: projects/$PROJECT_NUMBER/secrets/ed_ui_widget_ssh/versions/1
#     env: 'ED_WIDGET_SSH_KEY'
