workflows:
  gummy-bear-android-dev-workflow:
    name: gummy_bear android DEV workflow
    labels:
      - Android
      - DEV
    instance_type: mac_mini_m1
    environment:
        groups:
        - module_credentials
    
    scripts:
    - name: Script that uses an alternative SSH key
      script: | 
        #!/usr/bin/env bash
        echo "${CUSTOM_KEY_NAME}" > /tmp/ssh_key
        chmod 600 /tmp/ssh_key
        eval `ssh-agent -s`
        ssh-add /tmp/ssh_key
        flutter pub get 
        # enter the commands that require the key

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    