name: Release Tag on Version Change

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Install Dependencies
        run: flutter pub get

      - name: Check for Version Change
        id: version-check
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}')
          if git tag -l "$VERSION" | grep "$VERSION"; then
            echo "No version change. Skipping release."
            exit 0
          else
            echo "Version changed. Continuing with the release."
          fi

      - name: Extract Release Description from CHANGELOG.md
        id: extract-description
        run: |
          DESCRIPTION=$(awk -v version="$VERSION" '$0 ~ version, /\*\*\[[0-9]+\.[0-9]+\.[0-9]+\]/ {if (!/## /) print}' CHANGELOG.md | grep -v "## $VERSION")
          echo $DESCRIPTION
        shell: bash

      - name: Create Release Tag
        if: steps.version-check.outputs.result == 'success'
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}')
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag "$VERSION"
          git push origin "$VERSION"

      - name: Create GitHub Release
        if: steps.version-check.outputs.result == 'success'
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}')
          body="${DESCRIPTION}"
          echo "RELEASE_BODY=${body}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Use GitHub Release Info
        run: |
          echo "Version: $RELEASE_VERSION"
          echo "Body: $RELEASE_BODY"
        shell: bash
